### ISSUE TITLE
What does the 24hr restriction do?

### ISSUE THREAD

**Issue by Swiftnesses** [YouTwitFace/AntiUserbotBot#2]
Hi,

In the code I see a reference to 24 hours, I'd like my users *only* to be able to talk if they click the button, no matter how long it takes, can you confirm what this setting does?

Cheers.

**Comment by YouTwitFace** [comment]
After the user clicks the button, they can only send messages and no media for 24 hours.

**Comment by YouTwitFace** [comment]
Sorry for the late response.

**Comment by Swiftnesses** [comment]
No problems, I want to make it permanent, what is the best way to do this? Removing the button after x days would also be good (we can assume they're bots!).

**Comment by YouTwitFace** [comment]
You want to make users only be able to send messages and no media forever? Just remove the `until_date`.

**Comment by Swiftnesses** [comment]
Unless they click the button, obviously :-) Ideally I'd remove the button after 2 days, they can request to be manually enabled if need be...

**Comment by YouTwitFace** [comment]
Currently, when the user clicks the button, they can **only** send text message for 24 hours.

**Comment by Swiftnesses** [comment]
Any ideas how I can make it work like this...

User joins, upon joining they cannot post anything.

If they click the button, they're allowed to post all types (allowed by the group).

if they don't click the button with x hours, it's deleted and they need to ask for access manually.

Any help would be greatly appreciated, thanks!

**Comment by YouTwitFace** [comment]
> If they click the button, they're allowed to post all types (allowed by the group).

Remove `until_date` on [line 87](https://github.com/YouTwitFace/AntiUserbotBot/blob/master/index.js#L87)

> if they don't click the button with x hours, it's deleted and they need to ask for access manually.

You can try using `setTimeout` to delete the message and when they click, use `clearTimeout`.

**Comment by Swiftnesses** [comment]
First one makes sense, I'm rubbish with Node, any pointers on how I can implement the timed delete (any pointers would be superb!).

Thanks for the help :)

**Comment by YouTwitFace** [comment]
You can create a [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) with chat ids, user ids and the timeout.

```javascript
const map = new Map();

// new_chat_member
...
const timeout = setTimeout(() => {
	// delete reply or edit with "message expired. message an admin to be unmuted"
}, milliseconds);

map.set(`${chat_id}:${from_id}`, timeout);
...

// unmute
...
const key = `${chat_id}:${from_id}`;
clearTimeout(map.get(key));
map.delete(key);
...
```

**Comment by Swiftnesses** [comment]
Will try and copy and paste this until it works, need to figure out how to implement it into the present code :)

**Comment by Swiftnesses** [comment]
I guess it's simple for someone seasoned in Node, but feel it's beyond my capabilities after some trial and error :(

**Comment by YouTwitFace** [comment]
Feel free to [message me on telegram](https://t.me/TwitFace).

**Comment by Swiftnesses** [comment]
Thanks for the help getting this working :)

Code is here: [](https://gist.github.com/Swiftnesses/a281a092d255504fb8eca3d4328944d7)

**Comment by YouTwitFace** [comment]
:ok_hand:
